# Generated by Django 4.2.6 on 2023-10-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='noAvatar.png', null=True, upload_to='media/'),
        ),
    ]
